---
title: "Text for portfolio 2"
author: "Otto Sejrskild Santesson"
date: "4/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### TL;DR
We constructed a DAG that reflected the causal relationship we thought there would be in our made up phenomenon, which was how your level of fear of corona ultimately had an effect of your energy level.

We simulated data that we then checked whether it was coherent to our DAG through checking the conditional independencies of the DAG. We found no results that implied that our DAG was wrong.

We tried to get wrong inference by not accounting for the backdoor (i.e. conditioning on OCD) in the DAG when trying to get the estimate of the effect of 'corona fear' on 'energy level', which we did - when not accounting for the backdoor, we got a different estimate than when we did account for it.

Finally, we simulated some data that we deliberately tried to make so it didn't fit our DAG. Afterwards, we checked whether this was true by going through the same conditional independencies as before. We found that some of the conditional independencies didn't hold, which showed that the DAG was wrong.

### Long version:
We constructed a DAG that mapped the causal relationships we thought there are between the variables in the made-up phenomenon we have chosen to investigate in this assignment.
The chosen phenomenon is the one of the causal relation between the variables 'corona fear' and 'energy level' - more specifically how one's level of fear of getting infected by corona and the virus in general can ultimately affect your energy level through intervening variables.

The intervening variables in question is chosen on the basis of what we thought to be the most essential nodes in the DAG; these include the variables 'OCD', which is the the level of severity of OCD symptoms of the individual, 'sanitizing', which reflects how much you sanitize your hands during the day (i.e. disinfect or wash your hands), 'social exposure', which corresponds to how socially active you are in terms of the size of your social circle that you see on a regular basis, how many people you interact with in close proximity etc. Finally, we have included the variable 'germ level' in our causal model (DAG), which is a measure of the amount of virus of external origin present in your body.

On the basis of this, we constructed a DAG from these variables and their respective causal connections, which was then used as the model that we simulated our data from, i.e. we made sure that the simulated data had the same relationships that was implied by our DAG. Additionally, we also assessed which elemental forms of variable relations were present in the DAG.

Afterwards, we checked for any backdoors in the DAG that we needed to account for when we tested the conditional independencies of our DAG, independencies which we had found previously. We then went through all of the conditional independencies, which we were to expect given this specific DAG, to check whether we should falsify it or not. After checking all of the conditional independencies, we found no results that indicated that the DAG should be falsified.

We then tried to see whether not accounting for the backdoor imposed by the variable 'OCD' when assessing the effect of 'corona fear' on 'energy level' would lead to a wrong inference, i.e. whether the estimate of the full effect of 'corona fear' on 'energy level' (size of the coefficient) would be different if we did not condition on 'OCD' when calculating the estimate. As expected, when we didn't get the same estimate when we didn't account for the backdoor, thus leading to the wrong inference of the effect of 'corona fear' on 'energy level'.

Finally, we deliberately tried to simulate data that would not fit the DAG that we had made, which we did by changing how the variables were dependent on each other. By running the conditional independencies from before, we found that 3 did not hold, which resulted in the rejection of the DAGs fitness to the data, i.e. that the DAG is wrong.